charts/testkube-cloud-api/README.md, charts/testkube-cloud-api/templates/deployment.yaml, charts/testkube-cloud-api/values.yaml
=> feat: allow to configure from email

charts/testkube-cloud-api/README.md, charts/testkube-cloud-api/templates/_helpers.tpl, charts/testkube-cloud-api/templates/deployment.yaml, charts/testkube-cloud-api/templates/ingress-minio.yaml, charts/testkube-cloud-api/templates/ingress-statuspages.yaml, charts/testkube-cloud-api/templates/migrations-job.yaml, charts/testkube-cloud-api/templates/minio.yaml, charts/testkube-cloud-api/values.yaml, charts/testkube-enterprise/README.md, charts/testkube-enterprise/values.yaml
=> feat: add minio ingress

charts/testkube-cloud-api/README.md, charts/testkube-enterprise/README.md, charts/testkube-enterprise/docs/README.md
=> docs: enterprise

charts/testkube-cloud-api/templates/deployment.yaml, charts/testkube-cloud-api/values.yaml
=> fix: dashboard endpoint

charts/testkube-enterprise/values.yaml
=> feat: add server name for nats

charts/testkube-enterprise/local-values.yaml
=> fix: update values file

.github/workflows/chart-release.yaml
=> ci: Update chart-release.yaml

charts/testkube-enterprise/local-values.yaml
=> values: update local values 

charts/testkube-cloud-api/templates/deployment.yaml, charts/testkube-cloud-api/values.yaml, charts/testkube-enterprise/values.yaml
=> feat: set healthcheck mode

.github/workflows/chart-release-dispatch.yaml, .github/workflows/chart-release.yaml, scripts/sync.sh
=> ci: add sync for local values file

charts/testkube-cloud-api/templates/deployment.yaml, charts/testkube-cloud-api/values.yaml, charts/testkube-enterprise/values.yaml
=> feat: testkube-enterprise: add parameters for enabling debug logs and keepalive

charts/testkube-cloud-api/.argocd-source-edge-testkube-cloud-api.yaml, charts/testkube-cloud-api/.argocd-source-norauto-testkube-cloud-api.yaml, charts/testkube-cloud-api/templates/deployment.yaml, charts/testkube-cloud-api/values.yaml, charts/testkube-cloud-ui/.argocd-source-edge-testkube-cloud-ui.yaml, charts/testkube-enterprise/.argocd-source-dev-testkube-enterprise.yaml, charts/testkube-enterprise/.argocd-source-edge-testkube-enterprise.yaml, charts/testkube-enterprise/installer_enterprise.sh, charts/testkube-enterprise/local-values.yaml, charts/testkube-enterprise/values.yaml, charts/testkube-worker-service/.argocd-source-edge-testkube-worker-service.yaml
=> feat: main merge 06-03-2025

charts/testkube-enterprise/local-values.yaml, charts/testkube-enterprise/values.yaml
=> fix: image tags versions

charts/testkube-cloud-ui/.argocd-source-dev-testkube-cloud-ui.yaml, charts/testkube-cloud-ui/.argocd-source-prod-testkube-cloud-ui.yaml, charts/testkube-cloud-ui/Chart.yaml, charts/testkube-cloud-ui/README.md, charts/testkube-cloud-ui/values.yaml, charts/testkube-enterprise/Chart.lock, charts/testkube-enterprise/Chart.yaml, charts/testkube-enterprise/README.md, charts/testkube-enterprise/local-values.yaml, charts/testkube-enterprise/values.yaml
=> Main to dev

charts/testkube-cloud-api/templates/deployment.yaml, charts/testkube-cloud-api/values.yaml
=> feat: logs service install params

.github/workflows/dispatch-develop-push.yaml
=> feat: dispatch event to deployment repo on push to develop

charts/testkube-cloud-api/templates/deployment.yaml, charts/testkube-cloud-api/values.yaml, charts/testkube-enterprise/local-values.yaml, charts/testkube-enterprise/values.yaml
=> feat: allow enable disable logs integration on api level

charts/testkube-enterprise/installer_enterprise.sh
Draft PR including some improvements at the simple installer bash script:
- New log feature
- Improved user experience reducing logs and making them more user friendly
- Reorganized the code including some helper functions
- Limited some while-true loops to avoid infinite retries, aborting after a certain amount of attempts.
=> feat: [TKC-1616] Optimization of log and preparation for telemetry

charts/testkube-cloud-api/templates/deployment.yaml, charts/testkube-cloud-api/values.yaml
=> feat: join demo - org id in env vars 

.github/workflows/chart-release-dispatch.yaml, .github/workflows/chart-release.yaml
=> fix: fix chart release

charts/testkube-cloud-ui/templates/deployment.yaml, charts/testkube-cloud-ui/values.yaml, charts/testkube-enterprise/profiles/values.demo.yaml
=> feat(demo): add Dex signup

charts/testkube-enterprise/profiles/values.demo.yaml
=> chore: fix signup URL

charts/testkube-cloud-api/templates/tests/test-connection.yaml, charts/testkube-cloud-api/values.yaml, charts/testkube-cloud-ui/templates/tests/test-connection.yaml, charts/testkube-cloud-ui/values.yaml, charts/testkube-enterprise/values.yaml
=> feat: disable test Connection pods

charts/testkube-enterprise/profiles/values.demo.yaml
=> fix: fix Dex signup in demo

charts/testkube-enterprise/local-values.yaml, charts/testkube-enterprise/profiles/values.demo.yaml, charts/testkube-enterprise/values.yaml
=> feat: added values for OpenShift installation

charts/testkube-cloud-api/templates/_helpers.tpl, charts/testkube-cloud-ui/templates/_helpers.tpl, charts/testkube-logs-service/templates/_helpers.tpl, charts/testkube-worker-service/templates/_helpers.tpl
=> revert: fix image tag

charts/testkube-cloud-api/templates/_helpers.tpl, charts/testkube-cloud-api/templates/certificate.yaml
=> feat: remove health workaround from api chart

charts/testkube-enterprise/values.yaml
=> fix: worker service use minio

charts/testkube-enterprise/profiles/values.demo.yaml, charts/testkube-enterprise/templates/shared-secrets/job.yaml, charts/testkube-enterprise/values.yaml
=> feat: change testkubeenterprise registry to kubeshop

charts/testkube-cloud-api/templates/deployment.yaml, charts/testkube-enterprise/README.md, charts/testkube-enterprise/profiles/values.demo.yaml, charts/testkube-enterprise/values.yaml
=> fix: add configuring for accessing the artifacts from on prem

charts/testkube-enterprise/values.yaml
=> feat: TKC-2092-update-resources

charts/testkube-enterprise/profiles/values.demo.yaml
=> chore: testkube-enterprise: cleanup demo profile

charts/testkube-cloud-api/templates/deployment.yaml, charts/testkube-cloud-api/values.yaml, charts/testkube-enterprise/README.md, charts/testkube-enterprise/values.yaml, charts/testkube-worker-service/templates/deployment.yaml, charts/testkube-worker-service/values.yaml
=> feat: testkube-enterprise: move nats and mongo config global

charts/testkube-cloud-api/templates/ingress-grpc.yaml, charts/testkube-cloud-api/templates/ingress-rest.yaml, charts/testkube-cloud-api/templates/ingress-ws.yaml, charts/testkube-cloud-api/values.yaml, charts/testkube-cloud-ui/templates/ingress-redirect.yaml, charts/testkube-cloud-ui/templates/ingress.yaml, charts/testkube-enterprise/templates/ingress-minio.yaml, charts/testkube-enterprise/values.yaml
- Add an option to make Ingress annotations custom
Checklist:
=> feat: update ingress

charts/testkube-cloud-api/templates/deployment.yaml, charts/testkube-cloud-api/templates/ingress-rest.yaml, charts/testkube-cloud-api/values.yaml, charts/testkube-enterprise/values.yaml
=> fix: email configuration checks to account for sendgrid

charts/testkube-enterprise/values.yaml
=> feat: specify resource and requests for nats containers

.github/workflows/dispatch-develop-push.yaml, .github/workflows/dispatch-sandbox-push.yaml
=> feat: use of github APP token

.github/workflows/dispatch-sandbox-delete.yaml
=> ci: add sandbox removal

charts/testkube-cloud-ui/templates/deployment.yaml, charts/testkube-cloud-ui/values.yaml
=> fix: API endpoint

.github/sandbox-comment-template.md, .github/workflows/dispatch-sandbox-push.yaml
=> ci: add outputs to sandbox env

charts/testkube-cloud-api/templates/_helpers.tpl, charts/testkube-cloud-api/templates/deployment.yaml, charts/testkube-cloud-api/templates/migrations-job.yaml, charts/testkube-cloud-api/values.yaml
=> feat: add support for defining registry for wait for mongo init container

charts/testkube-enterprise/profiles/values.demo.yaml
=> feat: enable migrations in demo installer

charts/testkube-enterprise/values.yaml
=> fix: enable enterprise migrations

charts/testkube-cloud-api/README.md, charts/testkube-cloud-api/templates/migrations-job.yaml, charts/testkube-cloud-api/values.yaml, charts/testkube-enterprise/README.md, charts/testkube-enterprise/values.yaml
=> fix: using same migrations image as in deployment and remove ttl for migration job

.github/workflows/dispatch-sandbox-push.yaml
=> ci: add checkout action to sandbox ci

charts/testkube-cloud-api/templates/deployment.yaml, charts/testkube-cloud-api/values.yaml, charts/testkube-enterprise/values.yaml
Add support for configuring audit logs
=> feat: TKC-2705: add config support for audit logs

charts/testkube-enterprise/values.yaml, charts/testkube-worker-service/templates/_helpers.tpl, charts/testkube-worker-service/templates/deployment.yaml, charts/testkube-worker-service/values.yaml
=> feat: update image for Mongo init container

charts/testkube-cloud-ui/templates/deployment.yaml, charts/testkube-cloud-ui/values.yaml
=> feat: pass TK_AI_TOKEN to the frontend

charts/testkube-cloud-api/templates/_helpers.tpl, charts/testkube-cloud-api/templates/deployment.yaml, charts/testkube-cloud-api/templates/migrations-job.yaml, charts/testkube-cloud-ui/templates/_helpers.tpl, charts/testkube-cloud-ui/templates/deployment.yaml, charts/testkube-enterprise/Chart.lock, charts/testkube-enterprise/Chart.yaml, charts/testkube-enterprise/charts/dex/Chart.yaml, charts/testkube-enterprise/charts/dex/templates/_helpers.tpl, charts/testkube-enterprise/charts/dex/templates/deployment.yaml, charts/testkube-enterprise/charts/nats/Chart.yaml, charts/testkube-enterprise/charts/nats/files/stateful-set/reloader-container.yaml, charts/testkube-enterprise/templates/shared-secrets/job.yaml, charts/testkube-enterprise/values.yaml, charts/testkube-logs-service/templates/_helpers.tpl, charts/testkube-logs-service/templates/deployment.yaml, charts/testkube-worker-service/templates/_helpers.tpl, charts/testkube-worker-service/templates/deployment.yaml
=> fix: securtiyContext

charts/testkube-cloud-ui/templates/deployment.yaml, charts/testkube-cloud-ui/values.yaml
=> feat: pass AI API uri and some defaults

charts/testkube-enterprise/values.yaml
=> feat: update Agent description in values

charts/testkube-enterprise/values.yaml
=> feat: update values description

charts/testkube-cloud-api/README.md, charts/testkube-cloud-api/templates/_helpers.tpl, charts/testkube-cloud-api/templates/deployment.yaml, charts/testkube-cloud-api/templates/migrations-indexes-job.yaml, charts/testkube-cloud-api/templates/migrations-job.yaml, charts/testkube-cloud-api/values.yaml, charts/testkube-enterprise/README.md, charts/testkube-enterprise/charts/dex/README.md, charts/testkube-enterprise/charts/dex/README.md.gotmpl, charts/testkube-enterprise/values.yaml
=> feat: added new separated migration job

charts/testkube-cloud-api/templates/deployment.yaml
=> fix: add tmp directory for checking out git repos in test discovery 

charts/testkube-cloud-ui/templates/deployment.yaml
=> feat: enable insight boards

.github/workflows/chart-release.yaml, .github/workflows/update-charts-dispatch.yaml, scripts/sync.sh
=> ci: update dispatch

charts/testkube-cloud-api/templates/servicemonitor.yaml, charts/testkube-cloud-api/values.yaml
=> feat: add sampleLimit for prometheus serviceMonitor

charts/testkube-enterprise/values.yaml
=> feat: update bitnami

charts/testkube-cloud-api/values.yaml
=> fix: fix missing github property in values.yaml

charts/testkube-ai-service/Chart.yaml, charts/testkube-ai-service/values.yaml
=> fix: ai service app version

charts/testkube-cloud-api/values.yaml, charts/testkube-cloud-ui/values.yaml, charts/testkube-enterprise/values.yaml, charts/testkube-worker-service/values.yaml
=> feat: update image docker repos

charts/testkube-ai-service/templates/deployment.yaml, charts/testkube-ai-service/values.yaml
add support for custom LLM API configuration in deployment and values files
=> feat: AI service custom LLM API configuration

charts/testkube-ai-service/templates/deployment.yaml, charts/testkube-ai-service/templates/external-secret.yaml, charts/testkube-ai-service/values.yaml
=> feat: add external secrets CRDs to ai service

charts/testkube-ai-service/templates/deployment.yaml, charts/testkube-ai-service/values.yaml
=> refactor: remove unnecessary env vars from ai service

charts/testkube-ai-service/templates/external-secret.yaml
=> fix: external secret use for ai service

charts/testkube-cloud-api/templates/deployment.yaml, charts/testkube-cloud-api/values.yaml, charts/testkube-enterprise/Chart.lock, charts/testkube-enterprise/Chart.yaml
=> chore: improve probe configurability

charts/testkube-enterprise/values.yaml
=> fix: add missing CLI client ID

charts/testkube-enterprise/profiles/values.demo.yaml, charts/testkube-enterprise/templates/dex-config-secret.yaml
=> fix: add CLI static client for demo profile

charts/testkube-enterprise/values.yaml
=> feat: enable multi-agent on-prem

charts/testkube-cloud-ui/values.yaml
=> feat: enable multi-agent

charts/testkube-cloud-api/README.md, charts/testkube-cloud-api/values.yaml, charts/testkube-enterprise/README.md, charts/testkube-enterprise/profiles/values.demo.yaml, charts/testkube-enterprise/values.yaml
=> fix: remove auto-accept inviteMode

scripts/sync.sh
=> fix: ai image tag update

.github/workflows/update-charts-dispatch.yaml
=> chore: update dashboard from monorepo builds

.github/workflows/update-charts-dispatch.yaml
=> chore: update ai service on monorepo change

charts/testkube-cloud-api/templates/_helpers.tpl, charts/testkube-cloud-api/templates/deployment.yaml
=> fix: fix helpers

charts/testkube-worker-service/values.yaml
=> fix: fix missing tag suffix
