kubeshop/testkube-cloud-charts

charts/testkube-cloud-ui/templates/ingress-redirect.yaml, charts/testkube-cloud-ui/values.yaml, charts/testkube-enterprise/values.yaml
=> feat: add redirect 

charts/testkube-enterprise/installer_enterprise.sh, charts/testkube-enterprise/local-values.yaml
=> values: enterprise

charts/testkube-enterprise/installer_enterprise.sh
This PR enables choosing a namespace for Testkube Agent in installer script. 
Checklist:
=> feat: add option to specify ns for the agent

charts/testkube-cloud-api/.argocd-source-dev-testkube-cloud-api.yaml, charts/testkube-cloud-api/.argocd-source-prod-testkube-cloud-api.yaml, charts/testkube-cloud-api/Chart.yaml, charts/testkube-cloud-api/README.md, charts/testkube-cloud-api/values.yaml, charts/testkube-cloud-ui/.argocd-source-dev-testkube-cloud-ui.yaml, charts/testkube-cloud-ui/.argocd-source-prod-testkube-cloud-ui.yaml, charts/testkube-cloud-ui/Chart.yaml, charts/testkube-cloud-ui/README.md, charts/testkube-cloud-ui/values.yaml, charts/testkube-enterprise/Chart.lock, charts/testkube-enterprise/Chart.yaml, charts/testkube-enterprise/README.md, charts/testkube-enterprise/local-values.yaml, charts/testkube-enterprise/values.yaml, charts/testkube-worker-service/.argocd-source-dev-testkube-worker-service.yaml
=> merge main to develop

charts/testkube-cloud-ui/.argocd-source-dev-testkube-cloud-ui.yaml, charts/testkube-cloud-ui/.argocd-source-prod-testkube-cloud-ui.yaml, charts/testkube-cloud-ui/Chart.yaml, charts/testkube-cloud-ui/README.md, charts/testkube-cloud-ui/values.yaml, charts/testkube-enterprise/Chart.lock, charts/testkube-enterprise/Chart.yaml, charts/testkube-enterprise/README.md, charts/testkube-enterprise/local-values.yaml, charts/testkube-enterprise/values.yaml
* Update `testkube-cloud-ui` for installer
=> Main to dev

charts/testkube-enterprise/installer_enterprise.sh
=> fox: point installer to helm chart main

charts/testkube-enterprise/values.yaml
=> fix: enteprise valid logs port number

charts/testkube-cloud-api/templates/deployment.yaml, charts/testkube-cloud-api/values.yaml, charts/testkube-enterprise/values.yaml
=> feat: inject custom ca into the enterprise api

charts/testkube-cloud-api/templates/deployment.yaml, charts/testkube-cloud-api/values.yaml, charts/testkube-enterprise/values.yaml
=> feat: add support for readpref and agent storage host overrides

charts/testkube-enterprise/installer_enterprise.sh
=> fix: use consistent machine id for telemetry

charts/testkube-cloud-api/values.yaml, charts/testkube-enterprise/local-values.yaml, charts/testkube-enterprise/values.yaml
Cherry-pick of #139 back to `develop`.
Checklist:
=> fix: improve docs for offline license and deprecate ineffective enterpriseLicenseFile field

charts/testkube-cloud-api/templates/_helpers.tpl, charts/testkube-cloud-api/templates/bootstrap-config.yaml, charts/testkube-cloud-api/templates/deployment.yaml, charts/testkube-cloud-ui/templates/_helpers.tpl, charts/testkube-cloud-ui/templates/deployment.yaml, charts/testkube-enterprise/profiles/values.demo.yaml, charts/testkube-enterprise/templates/_helpers.tpl, charts/testkube-enterprise/templates/shared-secrets/job.yaml, charts/testkube-enterprise/values.yaml, charts/testkube-logs-service/templates/_helpers.tpl, charts/testkube-logs-service/templates/deployment.yaml, charts/testkube-worker-service/templates/_helpers.tpl, charts/testkube-worker-service/templates/deployment.yaml
This PR:
- Removes bootstrapAdmin by leveraging default_organization and default_environments to auto-join. This is for the demo profile. The benefit is that it's easier to use different e-mails than admin@example.com as it only has to be updated in one place and that multiple admins can also exist.
- Introduces registry overrides by Bitnami standard, i.e. `global.imageRegistry`.
=> fix: image registry override

charts/testkube-enterprise/values.yaml
=> fix: use Minio as default storage for worker service

charts/testkube-enterprise/values.yaml
=> fix: make default minio endpoint not-namespace specific

charts/testkube-cloud-api/templates/_helpers.tpl, charts/testkube-cloud-api/values.yaml, charts/testkube-cloud-ui/templates/_helpers.tpl, charts/testkube-cloud-ui/values.yaml, charts/testkube-enterprise/README.md, charts/testkube-enterprise/values.yaml, charts/testkube-logs-service/templates/_helpers.tpl, charts/testkube-logs-service/values.yaml, charts/testkube-worker-service/templates/_helpers.tpl, charts/testkube-worker-service/values.yaml
If you want to define common labels (labels which will be applied to all Kubernetes resources), set the following parameter:
```
global:
labels:
foo: bar
```
=> feat: testkube-enterprise: add support for defining common labels

charts/testkube-enterprise/profiles/values.demo.yaml, charts/testkube-enterprise/values.yaml
=> testkube-enterprise: pinpoint enterprise worker service to v1.9.1

charts/testkube-cloud-api/values.yaml, charts/testkube-enterprise/local-values.yaml, charts/testkube-enterprise/templates/dex-config-secret.yaml, charts/testkube-enterprise/values.yaml
=> fix: remove dependence on ingresses for dex configuration

charts/testkube-cloud-api/templates/deployment.yaml, charts/testkube-cloud-api/values.yaml, charts/testkube-enterprise/values.yaml
Also sets the default invitte mode to "auto-accept" to ease the basic installations.
**Note**, this is technically a breaking change as we are changing default values.
Checklist:
=> feat: require smtp/email setup in the "email" invite mode

charts/testkube-cloud-api/values.yaml
=> fix: testkube-cloud-api: change default invite mode to email

charts/testkube-enterprise/profiles/values.demo.yaml, charts/testkube-enterprise/templates/dex-config-secret.yaml, charts/testkube-enterprise/values.yaml
Fix issue where `staticClients` block is duplicated in Dex.
Move base Dex settings from demo profile to parent values.yaml
Add setting to skip additional Dex approval screen.
Checklist:
=> chore: cleanup dex config in profile and move common config to parent values yaml

charts/testkube-cloud-api/templates/_helpers.tpl, charts/testkube-cloud-ui/templates/_helpers.tpl, charts/testkube-logs-service/templates/_helpers.tpl, charts/testkube-worker-service/templates/_helpers.tpl
Skaffold's uses image tags which are longer than 63 characters which is a prohibited length for Kubernetes labels. This allows disabling adding those labels.
=> fix: remove version label

charts/testkube-enterprise/values.yaml, charts/testkube-worker-service/templates/deployment.yaml, charts/testkube-worker-service/values.yaml
=> feat: add an option to disable mongo init container for Worker service

charts/testkube-cloud-api/templates/deployment.yaml, charts/testkube-cloud-api/templates/migrations-job.yaml, charts/testkube-cloud-ui/templates/deployment.yaml, charts/testkube-enterprise/Chart.lock, charts/testkube-enterprise/Chart.yaml, charts/testkube-enterprise/charts/dex/Chart.yaml, charts/testkube-enterprise/charts/dex/templates/deployment.yaml, charts/testkube-enterprise/values.yaml, charts/testkube-logs-service/templates/deployment.yaml, charts/testkube-worker-service/templates/deployment.yaml
=> feat: update global image secrets

charts/testkube-cloud-api/templates/deployment.yaml, charts/testkube-cloud-api/values.yaml
Even though there exists a field called `additionalEnv`, it can only be used as a envvar->value map, but we need also a solution to add additional envvars from secrets. Also, the `additionalEnv` is already used internally and by customers so we cannot remove it easily.
The new field `additionalEnvVars` supports an array of EnvVar objects (name, value, valueFrom...)
Checklist:
=> feat: testkube-cloud-api: add support for additional env var references

charts/testkube-enterprise/Chart.lock, charts/testkube-enterprise/Chart.yaml, charts/testkube-enterprise/charts/dex/Chart.yaml, charts/testkube-enterprise/charts/dex/templates/ingress.yaml
=> feat: disable dex ingress if globals are also disabled

charts/testkube-ai-service/templates/deployment.yaml, charts/testkube-ai-service/values.yaml, charts/testkube-enterprise/values.yaml
=> chore: add extra env vars to ai service chart

charts/testkube-enterprise/templates/shared-secrets/job.yaml, charts/testkube-enterprise/values.yaml
Requested by customer Virta Health to be able to add Istio labels.
Checklist:
=> feat: add additional annotations property for job secret-generator

charts/testkube-enterprise/profiles/values.demo.yaml, charts/testkube-enterprise/templates/dex-config-secret.yaml, charts/testkube-enterprise/values.yaml
Add dex redirect uri for 38090 port
Checklist:
=> fix: [TKC-2802] add redirect uri

charts/testkube-ai-service/templates/deployment.yaml
=> fix: set key for env name

charts/testkube-enterprise/templates/dex-config-secret.yaml
=> fix: dex static client for CLI testkube typo

charts/testkube-enterprise/templates/dex-config-secret.yaml
=> fix: allow Testkube Enterprise to redirect back to the Testkube CLI

charts/testkube-enterprise/templates/dex-config-secret.yaml
=> fix: make the CLI Dex client public

charts/testkube-enterprise/profiles/values.demo.yaml
=> fix: provide correct agent host/port for demo profile

charts/testkube-cloud-api/templates/deployment.yaml, charts/testkube-cloud-api/values.yaml
=> feat: TKC-3519: add support for dex api url in testkube-cloud-api
